// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, name, account_type, currency, bank_name, last_four, nickname, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8 )
RETURNING id, user_id, name, balance, account_type, currency, bank_name, last_four, is_active, nickname, notes, created_at, updated_at
`

type CreateAccountParams struct {
	UserID      int64
	Name        string
	AccountType sql.NullString
	Currency    sql.NullString
	BankName    sql.NullString
	LastFour    sql.NullString
	Nickname    sql.NullString
	Notes       sql.NullString
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.AccountType,
		arg.Currency,
		arg.BankName,
		arg.LastFour,
		arg.Nickname,
		arg.Notes,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Balance,
		&i.AccountType,
		&i.Currency,
		&i.BankName,
		&i.LastFour,
		&i.IsActive,
		&i.Nickname,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, name, balance, account_type, currency, bank_name, last_four, is_active, nickname, notes, created_at, updated_at FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Balance,
		&i.AccountType,
		&i.Currency,
		&i.BankName,
		&i.LastFour,
		&i.IsActive,
		&i.Nickname,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountsByUser = `-- name: GetAccountsByUser :many
SELECT id, user_id, name, balance, account_type, currency, bank_name, last_four, is_active, nickname, notes, created_at, updated_at FROM accounts
WHERE user_id = $1
`

func (q *Queries) GetAccountsByUser(ctx context.Context, userID int64) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Balance,
			&i.AccountType,
			&i.Currency,
			&i.BankName,
			&i.LastFour,
			&i.IsActive,
			&i.Nickname,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
