// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type TokenBlacklist struct {
	Jti       string
	ExpiresAt time.Time
}

type User struct {
	ID           int64
	Name         string
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
