// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Account struct {
	ID          int64
	UserID      int64
	Name        string
	Balance     string
	AccountType sql.NullString
	Currency    sql.NullString
	BankName    string
	LastFour    string
	IsActive    sql.NullBool
	Nickname    sql.NullString
	Notes       sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Merchant struct {
	ID        int64
	Name      string
	Category  sql.NullString
	Website   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type TokenBlacklist struct {
	Jti       string
	ExpiresAt time.Time
}

type Transaction struct {
	ID               int64
	AccountID        int64
	Amount           string
	Type             string
	Description      sql.NullString
	Category         sql.NullString
	Status           sql.NullString
	ReferenceID      sql.NullString
	Metadata         pqtype.NullRawMessage
	InitiatedByUser  sql.NullBool
	RelatedAccountID sql.NullInt64
	IsSelfTransfer   sql.NullBool
	MerchantID       sql.NullInt64
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type User struct {
	ID           int64
	Name         string
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type UserMerchant struct {
	ID         int64
	UserID     int64
	MerchantID int64
	LastUsed   sql.NullTime
	UsageCount sql.NullInt32
}
